---
dist: xenial
language: python
python:
  - "3.7"
env:
  global:
    - MY_ENV=cnn
    - URL=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - BAM=data/test/chr12_chr22.44Mb_45Mb.GRCh37.bam
    - CHROM="12 22"
install:
  - sudo apt-get update
  - wget $URL -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -n $MY_ENV -f environment.yaml
  - conda activate -n $MY_ENV
script:
  - ./run_local.sh $BAM $CHROM
