---
dist: xenial
sudo: required
language: python
python:
  - "3.7"
services:
  - docker
addons:
  sonarcloud:
    organization: "gtcg"
    token:
      secure: "ig2eAvBCi0qn8Uz88cenkd5iEDF1bJO9C40NFHGeu/1icHAOaPqx/OVG+WCXxGPPgbm1rAQxc1fPI4VQcITxcJB0fivT7Ma/DY2cKYEMRiTIAuHWzGoYnmPunV6RUs/IguLF/yawSa+az6r3Whq52Xw0uUvmIkUTlX5VSWtLTekwiyQDLCSrsX1Kax0zptNVlMzFFWxETJLRywk/6o6VyG/uogvT7E0G2E7LIIctVWwdZ7jHXwIXkcFstg/9e2ayP5MlqOivP1VYoNxJc5FW2eS3T+GCzj9xKdrJIoRREbj+8qOY68ckc+BDvFQhgTF4Asfumkxu1SNtwVrhU6wZiROjoEFi53H27ve+PFZoCZipeevb28ec6KA9EWR5ILke59DiNYNfHlo2wv9jJRkEJLzoKT/qWCkW+CGslNZOrQ89AyrYG2lD3lQw0kmNH9/Pl7OC+eeX9wI9Bq7486AFfWH6wVc2Dh1dJanQTqveAxGnpn+BxjIu5HujCEs8ouTW+kgT/QJwqCEayQrD2teG5PSNbC/svgn6mkOIDctqqjM8nvAaCMY2uo4fQHpbQ8Aqe4h2muezEcIu63a2K8Szyo+91v+Rledx44521g8YCMPBJuMIrIZ/ke3xt16XU2b2D+kiwqQi6bdqdemJzImTAm16mr9EePBkotkutNl3mRI="
env:
  global:
    - PREFIX=gtcg/xenon
    - BAM=data/test.bam
    - SEQIDS="12,22"
    - SVTYPES="INV,DEL,INS,INV,DUP,CTX"
  matrix:
    - PORT=10024 IMG=gridengine TAG=6 SCH=local
    - PORT=10025 IMG=gridengine TAG=6 SCH=gridengine
    - PORT=10026 IMG=slurm TAG=19 SCH=slurm
install:
  - docker run -d -p $PORT:22 --name $SCH $PREFIX-$IMG:$TAG
  - sleep 10
  - docker ps -a
  - docker cp ./ $SCH:/home/xenon
  - docker exec -t $SCH chown -R xenon:xenon /home/xenon
  - docker exec -u xenon -t $SCH ./install.sh
script:
  - docker exec -u xenon -t $SCH ./run.sh $SCH $BAM $SEQIDS $SVTYPES
