---
dist: xenial
sudo: required
language: python
python:
  - "3.7"
services:
  - docker
env:
  global:
    - PREFIX=gtcg/xenon
    - BAM=data/test.bam
    - SEQIDS="12,22"
  matrix:
    - PORT=10024 IMG=gridengine TAG=6 SCH=local SV=DEL
    - PORT=10025 IMG=gridengine TAG=6 SCH=local SV=INS
    - PORT=10026 IMG=gridengine TAG=6 SCH=local SV=DUP
    - PORT=10027 IMG=gridengine TAG=6 SCH=local SV=INV
    - PORT=10028 IMG=gridengine TAG=6 SCH=local SV=CTX
    - PORT=10029 IMG=gridengine TAG=6 SCH=local SV=TRA
install:
  - docker run -d -p $PORT:22 --name $SCH $PREFIX-$IMG:$TAG
  - sleep 10
  - docker ps -a
  - docker cp ./ $SCH:/home/xenon
  - docker exec -t $SCH chown -R xenon:xenon /home/xenon
  - docker exec -u xenon -t $SCH ./install.sh
script:
  - docker exec -u xenon -t $SCH ./run.sh $SCH $BAM $SEQIDS $SV
