dist: trusty
sudo: required
language: python
python:
  - "3.6"
services:
  - docker
env:
  global:
    - PREFIX=gtcg/sv-callers
    - TAG=dev
    - HOME=/home/xenon/
    - BAM=data/test/hmz-sv.bam
  matrix:
    - PORT=10022 SCH=gridengine
    - PORT=10023 SCH=slurm
install:
  - docker pull $PREFIX-$SCH:$TAG
  - docker run -d -p $PORT:22 --name $SCH $PREFIX-$SCH:$TAG
  - sleep 10
  - docker ps -a
  - docker cp data/test/ $SCH:$HOME
  - docker cp scripts/genome_wide/ $SCH:$HOME
  - docker cp run.sh $SCH:$HOME
script:
  - docker exec -u xenon -t $SCH ls # run.sh $SCH $BAM
