dist: xenial
sudo: required
language: python
python:
  - "3.7"
services:
  - docker
env:
  global:
    - PREFIX=gtcg/xenon
    - TAG=dev
    - BAM=data/test/chr12_chr22.44Mb_45Mb.GRCh37.bam
    - CHR=12
  matrix:
    - PORT=10022 SCH=gridengine
    - PORT=10023 SCH=slurm
before_install:
  - docker pull $PREFIX-$SCH:$TAG
  - docker run -d -p $PORT:22 --name $SCH $PREFIX-$SCH:$TAG
  - sleep 10
  - docker ps -a
install:
  - docker cp ./ $SCH:/home/xenon
  - docker exec -t $SCH chown -R xenon.xenon /home/xenon
  - docker exec -u xenon -t $SCH ./install.sh
script:
  - docker exec -u xenon -t $SCH ./run.sh $SCH $BAM $CHR

