---
dist: xenial
sudo: required
language: python
python:
  - "3.7"
services:
  - docker
env:
  global:
    - PREFIX=gtcg/xenon
    - BAM=data/test.bam
    - SEQIDS="12,22"
  matrix:
    - PORT=10022 IMG=gridengine TAG=6 SCH=local
    - PORT=10023 IMG=gridengine TAG=6 SCH=gridengine
    - PORT=10024 IMG=slurm TAG=19 SCH=slurm
install:
  - docker run -d -p $PORT:22 --name $SCH $PREFIX-$IMG:$TAG
  - sleep 10
  - docker ps -a
  - docker cp ./ $SCH:/home/xenon
  - docker exec -t $SCH chown -R xenon:xenon /home/xenon
  - docker exec -u xenon -t $SCH ./install.sh
script:
  - docker exec -u xenon -t $SCH ./run.sh $SCH $BAM $SEQIDS
