---
dist: xenial
sudo: required
language: python
python:
  - "3.7"
services:
  - docker
addons:
  sonarcloud:
    organization: "gtcg"
    token:
      secure: "BI59w+Enx4ZDYbhM5DZANlbELOHPPt/cX+3G1AUZigtCkIMB2eY8QUMbF+mNYC+uYq18bAaNvY6Z5FeLnZNV9P6BZKs/qaSJ9SFd9sTUsUWlG65Mf0FWWrC2P+hcQUXOqNbgqJLaPAJnrUj49dxBx4x3tLdJsh+ziJv+0G31E1b4dlR5CHqGlsBbAt+rdyCx0fh38Jceh1jcQQJUsnESSznKLdN8Hcg5c/D1LY7D0k81RCy3yA+evGgAo69MmOa97dM07Qsxz2QytrNrf0/cW3kTH2v27eb0AhjEq8oMYrl5SA9dAOWY769+bnaGAABy50u0fRjnaFcbDIbRImC4LjpPMmZGwkVaRR+xWjtdSJ9XF8A9je2tTEAjL81/vLCZlutzY9oqJ7Z657LaSiqFDp5nXDtamYbXI3HkPt2f1bhU36YYWEXzkJZnzUVvw9T2gPidfMKy4UK/PLTOy624Eni8v5uHkeSIOrF++NUyz9h0NLsQyT1fIykPAolF1RaPJ5QU8ioeMBuT78Tm5JkHLoxpD3SJ/2QO7XQeA0ZZ3ClRs2RJletq9v6QGbDRTG3sYjQHdoKVG0BebIyEOZ38XFodpyLQ/oKDaYfO9i/Zc47cJHmVbKnsi41yFlx6HPLMTMtV+jyl6dv3BOrjZ0n2kn1pGo8vH7d30nXUQJRm6mc="

env:
  global:
    - PREFIX=gtcg/xenon
    - BAM=data/test.bam
    - SEQIDS="12,22"
  matrix:
    - PORT=10022 IMG=gridengine TAG=6 SCH=local
    - PORT=10023 IMG=gridengine TAG=6 SCH=gridengine
    - PORT=10024 IMG=slurm TAG=19 SCH=slurm
install:
  - docker run -d -p $PORT:22 --name $SCH $PREFIX-$IMG:$TAG
  - sleep 10
  - docker ps -a
  - docker cp ./ $SCH:/home/xenon
  - docker exec -t $SCH chown -R xenon:xenon /home/xenon
  - docker exec -u xenon -t $SCH ./install.sh
script:
  - docker exec -u xenon -t $SCH ./run.sh $SCH $BAM $SEQIDS
  - sonar-scanner
