channels:
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - intervaltree
  - pysam
  - numpy
  - pandas
  - bz2file
  - plotnine
  - pybigwig
  - twobitreader
  - bcolz
  - scikit-learn
  - tensorflow>=2.0.0
  - r-argparser
  - bioconductor-structuralvariantannotation
  - xenon-cli=3.0.5
  - jq
  - cigar
  - coreutils
