channels:
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - intervaltree
  - pysam
  - numpy
  - pandas
  - bz2file
  - plotnine
  - pybigwig
  - twobitreader
  - bcolz
  - r-argparser
  - bioconductor-structuralvariantannotation
  - xenon-cli
  - jq
