channels:
  - conda-forge
  - bioconda
  - r
  - nlesc
dependencies:
  - intervaltree
  - pysam
  - bwa
  - samtools
  - openssl=1.0
  - numpy
  - pandas
  - bz2file
  - plotnine
  - pybigwig
  - twobitreader
  - bcolz
  - scikit-learn
  - tensorflow>=2.0.0
  - r-argparser
  - bioconductor-structuralvariantannotation
  - xenon-cli=3.0.5
  - jq
  - cigar
  - biopython
  - coreutils
  - r-vcfr
  - rstudio
  - r-ggplot2
