channels:
  - conda-forge
  - r
  - bioconda
  - nlesc
dependencies:
  - biopython
  - bcolz
  - bz2file
  - coreutils
  - intervaltree
  - jq
  - plotnine
  - r-argparser
  - r-vcfr
  - scikit-learn
  - tensorflow
  - r-ggplot2
  - rstudio
  - cigar
  - bioconductor-structuralvariantannotation
  - pysam
  - pybigwig
  - twobitreader
  - xenon-cli=3.0.5
